const ACTION_TYPES = {
  GET_DATA_REQUEST: 'GET_DATA_REQUEST',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_ERROR: 'GET_DATA_ERROR',
  UPDATE_USER: 'UPDATE_USER',
  RESET_THEME: 'RESET_THEME',
  TOGGLE_THEME: 'TOGGLE_THEME',
};

export default ACTION_TYPES;
